COLUMN_MANY = 'MANY'
COLUMN_ONE = 'ONE'

COLUMN_TYPE_CONTINUOUS = 'CONTINUOUS'
COLUMN_TYPE_DISCRETE = 'DISCRETE'
COLUMN_TYPE_BOOLEAN = 'BOOLEAN'
COLUMN_TYPE_DATETIME = 'DATETIME'

STORAGE_TYPE_LOCAL_DB = 'LOCAL_DB'
STORAGE_TYPE_REMOTE_DB = 'REMOTE_DB'
STORAGE_TYPE_FILES = 'FILES'
