"""init

Revision ID: 094e92f88a51
Revises: 
Create Date: 2020-01-13 19:48:11.000068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094e92f88a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('column_source_name', sa.String(), nullable=True),
    sa.Column('column_custom_name', sa.String(), nullable=True),
    sa.Column('is_many', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_metadata_column_source_name'), 'column_metadata', ['column_source_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_dataset_name'), 'column_metadata', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_table_name'), 'column_metadata', ['table_name'], unique=False)
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder'),
    sa.UniqueConstraint('prefix')
    )
    op.create_index(op.f('ix_dataset_metadata_dataset_name'), 'dataset_metadata', ['dataset_name'], unique=True)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('db_location', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_location')
    )
    op.create_index(op.f('ix_table_metadata_dataset_name'), 'table_metadata', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_table_metadata_table_name'), 'table_metadata', ['table_name'], unique=False)
    op.create_table('table_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('reference_table', sa.String(), nullable=True),
    sa.Column('other_table', sa.String(), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=True),
    sa.Column('is_child', sa.Boolean(), nullable=True),
    sa.Column('is_sibling', sa.Boolean(), nullable=True),
    sa.Column('is_step_sibling', sa.Boolean(), nullable=True),
    sa.Column('reference_key', sa.String(), nullable=True),
    sa.Column('other_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_relationship_dataset_name'), 'table_relationship', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_child'), 'table_relationship', ['is_child'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_parent'), 'table_relationship', ['is_parent'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_sibling'), 'table_relationship', ['is_sibling'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_step_sibling'), 'table_relationship', ['is_step_sibling'], unique=False)
    op.create_index(op.f('ix_table_relationship_other_key'), 'table_relationship', ['other_key'], unique=False)
    op.create_index(op.f('ix_table_relationship_other_table'), 'table_relationship', ['other_table'], unique=False)
    op.create_index(op.f('ix_table_relationship_reference_key'), 'table_relationship', ['reference_key'], unique=False)
    op.create_index(op.f('ix_table_relationship_reference_table'), 'table_relationship', ['reference_table'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_table_relationship_reference_table'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_reference_key'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_other_table'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_other_key'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_step_sibling'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_sibling'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_parent'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_child'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_dataset_name'), table_name='table_relationship')
    op.drop_table('table_relationship')
    op.drop_index(op.f('ix_table_metadata_table_name'), table_name='table_metadata')
    op.drop_index(op.f('ix_table_metadata_dataset_name'), table_name='table_metadata')
    op.drop_table('table_metadata')
    op.drop_table('group')
    op.drop_index(op.f('ix_dataset_metadata_dataset_name'), table_name='dataset_metadata')
    op.drop_table('dataset_metadata')
    op.drop_index(op.f('ix_column_metadata_table_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_dataset_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_column_source_name'), table_name='column_metadata')
    op.drop_table('column_metadata')
    # ### end Alembic commands ###
