"""add_schema

Revision ID: 58a41d16df15
Revises: ccb4bf54cc61
Create Date: 2020-02-20 13:14:49.347617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a41d16df15'
down_revision = 'ccb4bf54cc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_metadata', sa.Column('schema', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_metadata', 'schema')
    # ### end Alembic commands ###
