"""metadata

Revision ID: 6ca90e1f698f
Revises: 2863fea98b08
Create Date: 2019-12-19 12:13:13.305489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca90e1f698f'
down_revision = '2863fea98b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('column_source_name', sa.String(), nullable=True),
    sa.Column('column_custom_name', sa.String(), nullable=True),
    sa.Column('is_many', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_metadata_column_source_name'), 'column_metadata', ['column_source_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_dataset_name'), 'column_metadata', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_table_name'), 'column_metadata', ['table_name'], unique=False)
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder')
    )
    op.create_index(op.f('ix_dataset_metadata_dataset_name'), 'dataset_metadata', ['dataset_name'], unique=True)
    op.create_table('table_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('db_location', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_metadata_dataset_name'), 'table_metadata', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_table_metadata_table_name'), 'table_metadata', ['table_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_metadata_table_name'), table_name='table_metadata')
    op.drop_index(op.f('ix_table_metadata_dataset_name'), table_name='table_metadata')
    op.drop_table('table_metadata')
    op.drop_index(op.f('ix_dataset_metadata_dataset_name'), table_name='dataset_metadata')
    op.drop_table('dataset_metadata')
    op.drop_index(op.f('ix_column_metadata_table_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_dataset_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_column_source_name'), table_name='column_metadata')
    op.drop_table('column_metadata')
    # ### end Alembic commands ###
