"""num_analyzed

Revision ID: 883c98f1145d
Revises: bd9d7375ca55
Create Date: 2020-02-10 11:06:42.374617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883c98f1145d'
down_revision = 'bd9d7375ca55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_metadata', sa.Column('num_analyzed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_metadata', 'num_analyzed')
    # ### end Alembic commands ###
