"""sql_links

Revision ID: 8d98871c147b
Revises: 094e92f88a51
Create Date: 2020-02-06 10:03:36.262617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d98871c147b'
down_revision = '094e92f88a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_metadata', sa.Column('sql_db', sa.String(), nullable=True))
    op.add_column('dataset_metadata', sa.Column('sql_server', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_metadata', 'sql_server')
    op.drop_column('dataset_metadata', 'sql_db')
    # ### end Alembic commands ###
