"""column_visibility

Revision ID: a174c7094c8b
Revises: f2c64b22c752
Create Date: 2019-12-31 12:09:54.117554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a174c7094c8b'
down_revision = 'f2c64b22c752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_metadata', 'visible')
    # ### end Alembic commands ###
