"""column_types

Revision ID: bd9d7375ca55
Revises: f819e31cc028
Create Date: 2020-02-06 14:05:15.037617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9d7375ca55'
down_revision = 'f819e31cc028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('data_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_metadata', 'data_type')
    # ### end Alembic commands ###
