"""stored_flag

Revision ID: ccb4bf54cc61
Revises: 883c98f1145d
Create Date: 2020-02-14 20:51:58.759981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb4bf54cc61'
down_revision = '883c98f1145d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_metadata', sa.Column('stored_in_data_db', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_metadata', 'stored_in_data_db')
    # ### end Alembic commands ###
