"""empty message

Revision ID: f2c64b22c752
Revises: 
Create Date: 2019-12-20 12:31:48.155149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c64b22c752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('column_source_name', sa.String(), nullable=True),
    sa.Column('column_custom_name', sa.String(), nullable=True),
    sa.Column('is_many', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_metadata_column_source_name'), 'column_metadata', ['column_source_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_dataset_name'), 'column_metadata', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_table_name'), 'column_metadata', ['table_name'], unique=False)
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder'),
    sa.UniqueConstraint('prefix')
    )
    op.create_index(op.f('ix_dataset_metadata_dataset_name'), 'dataset_metadata', ['dataset_name'], unique=True)
    op.create_table('table_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('db_location', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_location')
    )
    op.create_index(op.f('ix_table_metadata_dataset_name'), 'table_metadata', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_table_metadata_table_name'), 'table_metadata', ['table_name'], unique=False)
    op.create_table('table_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('reference_table', sa.String(), nullable=True),
    sa.Column('other_table', sa.String(), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=True),
    sa.Column('is_child', sa.Boolean(), nullable=True),
    sa.Column('is_sibling', sa.Boolean(), nullable=True),
    sa.Column('is_step_sibling', sa.Boolean(), nullable=True),
    sa.Column('reference_key', sa.String(), nullable=True),
    sa.Column('other_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_relationship_dataset_name'), 'table_relationship', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_child'), 'table_relationship', ['is_child'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_parent'), 'table_relationship', ['is_parent'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_sibling'), 'table_relationship', ['is_sibling'], unique=False)
    op.create_index(op.f('ix_table_relationship_is_step_sibling'), 'table_relationship', ['is_step_sibling'], unique=False)
    op.create_index(op.f('ix_table_relationship_other_key'), 'table_relationship', ['other_key'], unique=False)
    op.create_index(op.f('ix_table_relationship_other_table'), 'table_relationship', ['other_table'], unique=False)
    op.create_index(op.f('ix_table_relationship_reference_key'), 'table_relationship', ['reference_key'], unique=False)
    op.create_index(op.f('ix_table_relationship_reference_table'), 'table_relationship', ['reference_table'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_relationship_reference_table'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_reference_key'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_other_table'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_other_key'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_step_sibling'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_sibling'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_parent'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_is_child'), table_name='table_relationship')
    op.drop_index(op.f('ix_table_relationship_dataset_name'), table_name='table_relationship')
    op.drop_table('table_relationship')
    op.drop_index(op.f('ix_table_metadata_table_name'), table_name='table_metadata')
    op.drop_index(op.f('ix_table_metadata_dataset_name'), table_name='table_metadata')
    op.drop_table('table_metadata')
    op.drop_index(op.f('ix_dataset_metadata_dataset_name'), table_name='dataset_metadata')
    op.drop_table('dataset_metadata')
    op.drop_index(op.f('ix_column_metadata_table_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_dataset_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_column_source_name'), table_name='column_metadata')
    op.drop_table('column_metadata')
    # ### end Alembic commands ###
