"""num_rows

Revision ID: f819e31cc028
Revises: 8d98871c147b
Create Date: 2020-02-06 10:33:28.833617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f819e31cc028'
down_revision = '8d98871c147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('num_non_null', sa.Integer(), nullable=True))
    op.add_column('table_metadata', sa.Column('num_records', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_metadata', 'num_records')
    op.drop_column('column_metadata', 'num_non_null')
    # ### end Alembic commands ###
